### ISSUE TITLE
位置情報が返ってきません

### ISSUE THREAD

**Issue by wata909** [geolonia/community-geocoder#1]
サンプルに入っている「東京都千代田区霞が関1-3-1」で検索しても，緯度経度が表示されませんでいした。エラーを見ると，

`Access to fetch at 'https://geolonia.github.io/simple-geocoder/api/13/13101/131010002001.json' from origin 'https://community-geocoder.geolonia.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

`https://geolonia.github.io/simple-geocoder/api/13/13101/131010002001.json net::ERR_FAILED`

となっていました。
環境はWindows10 Pro, Chrome 83.0.4103.61（Official Build） （64 ビット）です。

**Comment by miya0001** [comment]
あっ、すいません、ちょうど今インフラの構成を変えたりいろいろしていました！
数分で解決するはずです！汗

**Comment by miya0001** [comment]
あと独自ドメインにしたので JavaScript API の URL を以下のように変更していただけると幸いです。

https://community-geocoder.geolonia.com/api.js

**Comment by miya0001** [comment]
解決したので閉じさせていただきます。
