### ISSUE TITLE
Script が発行するURLの先が 404 を返却する

### ISSUE THREAD

**Issue by technokuro** [geolonia/community-geocoder#122]
https://community-geocoder.geolonia.com/api/12/12102/12102.json
Scriptで決定された上記URLが 404 を返却するため、緯度経度を取得できませんでした。

**Comment by miya0001** [comment]
@technokuro フィードバックありがとうございます！
先日アップデートをしたのですが、その際に作業ミスがあったようです。
現在は修正されていると思いますので、ご確認いただけますと幸いです。

**Comment by technokuro** [comment]
@miya0001 さん
修正対応ありがとうございます。
ただ、状況は悪化しまして、getLatLng の参照が取れないようです。

当方のソースは以下（抜粋）となっています。
今までは 、onFail が動作していたのですが、現在は getLatLng そのものの参照がなく、onThrowが実行されるようになりました。
```
try{
  getLatLng(xxxxx, (latlng) => {
       onSuccess();
  }, (err) => {
       onFail();
  });
}catch(e){
  onThrow(e);
}
```

**Comment by ionlionsion** [comment]
横から失礼いたします。
こちらでも本日、以下エラーが表示されてしまうようです。

`Uncaught ReferenceError: getLatLng is not defined`

**Comment by keichan34** [comment]
@technokuro @ionlionsion 大変申し訳ありません。
`getLatLng` が以前 `window` につけましたが、先日のリリースで間違って `window` に設定する箇所を変えてしまいました。
修正版をデプロイしましたので、ご確認いただけばと思います。

**Comment by ionlionsion** [comment]
@miya0001 
早々のご対応ありがとうございます。確認させていただきました。

**Comment by technokuro** [comment]
修正を確認しました。
ありがとうございました。
@miya0001
