### ISSUE TITLE
[誤判定] 埼玉県比企郡鳩山町石坂

### ISSUE THREAD

**Issue by smellman** [geolonia/community-geocoder#14]
住所が判定できませんでした。

この住所は東京電機大学鳩山キャンパスを指しています。
地番はありません。
地理院地図では以下の場所に飛びます。
https://maps.gsi.go.jp/#16/35.988640/139.368225/&base=std

**Comment by miya0001** [comment]
@smellman #18 と同じ原因でした。以下のコミットで治りました。
https://github.com/geolonia/community-geocoder/commit/da3a3037c5c1471a309a69e4450a68228fb89862
