### ISSUE TITLE
[誤判定] 長野県松本市岡田松岡１６２－１

### ISSUE THREAD

**Issue by torounit** [geolonia/community-geocoder#15]
住所が判定できませんでした。

https://map.japanpost.jp/p/search/dtl/300111754000/
https://www.google.com/maps?q=36.2612131,137.9761303

長野県松本市岡田松岡
長野県松本市**大字**岡田松岡

のどちらの表記もあるようです。

**Comment by miya0001** [comment]
ありがとうございます！対処しました！
