### ISSUE TITLE
[誤判定？]富山県中新川郡立山町横江31

### ISSUE THREAD

**Issue by tkusano** [geolonia/community-geocoder#16]
富山県中新川郡立山町横江31
https://yahoo.jp/WRpuqM

富山県中新川郡立山町横江31
https://yahoo.jp/3yNKDf

昭和29年の2つの町の合併によって離れた場所に同じ地名が2箇所に存在するようなってしまった事例です。かぶっている地番もあるみたいです。
https://twitter.com/AB1QQ/status/1268418853903556608 より

**Comment by miya0001** [comment]
おおお、貴重な情報をありがとうございます！

**Comment by miya0001** [comment]
Geocoder としては不具合があるものの、住所の正規化としてはうまく動作してるので閉じさせていただきます！
