### ISSUE TITLE
[誤判定] 埼玉県所沢市上安松

### ISSUE THREAD

**Issue by kazuau** [geolonia/community-geocoder#18]
住所が判定できませんでした。
(Qiitaの記事を見て早速です)

全国的にそれなりにみられるパターンだと思います。

この大字は正式には「埼玉県所沢市大字上安松」です。
しかし、ここの郵便番号を日本郵政のサイトで検索すると
https://www.post.japanpost.jp/cgi-zip/zipcode.php?zip=3590025
「所沢市上安松」となることで分かるように、通称としては「大字」が省かれます。

番地から住居表示に移行するときに「大字」や「字」を省くことが多いようですが
住居表示と地番がまだ混在している市町村では、住居表示に移行していない地域も省くことが散見されるように思います。

(追記)
日本郵政のサイトでは埼玉県の「上安松」で検索できますが「大字上安松」では「該当する地名を特定できませんでした」になります。

**Comment by miya0001** [comment]
貴重な情報をありがとうございます！
埼玉はそれほど特別な感じはしないですが、判定できない事例が多いですね。なぜなんだろ。。。

**Comment by miya0001** [comment]
ありがとうございます！ 修正しました！
