### ISSUE TITLE
[誤判定] 札幌市西区24軒1-1

### ISSUE THREAD

**Issue by uraran** [geolonia/community-geocoder#20]
住所が判定できませんでした。
(札幌市西区二十四軒1条1丁目 緯度43.073824 経度141.318126 が正)

https://rousai-kensaku.mhlw.go.jp/list.php?mod=1&page=20
> 札幌市西区２４軒２条２－４－３０
こちらのようにアラビア数字表記が使用されるケースがあり、また公道の地点案内標識でも「24軒」表記が一部現存します。

(札幌市西区八軒ではあまり見かけませんが、少数でも同様のケースが存在するよう)

**Comment by miya0001** [comment]
おおお、`軒` とは！ ありがとうございます！

**Comment by miya0001** [comment]
修正しました！ありがとうございます！！
