### ISSUE TITLE
京都市中京区蛸薬師通高倉西入泉正寺町334

### ISSUE THREAD

**Issue by iot-dojo** [geolonia/community-geocoder#21]
「京都府京都市中京区泉正寺町３２６西川ビル」のあたりに誤判定されます。

**Comment by iot-dojo** [comment]
New

**Comment by iot-dojo** [comment]
Update Title

**Comment by miya0001** [comment]
ありがとうございます！

このジオコーダーは、「大字町丁目」レベルまでしか対応していなくて、確認した結果これでも意図したとおりには判別できているようです。
まだまだイマイチな精度で恐縮ですが、これから育てていくところですので気長に見守っていただけると幸いです。

というわけで本件閉じさせていただきます。ありがとうございました！
