### ISSUE TITLE
[誤判定]京都府京都市中京区元竹田町６２５

### ISSUE THREAD

**Issue by iot-dojo** [geolonia/community-geocoder#22]
「京都府京都市中京区元竹田町６３１」あたりを指してしまいます。
緯度経度の問題ではなく、趣旨違いでしたらすみません。

**Comment by miya0001** [comment]
あっ、すいません。
本件も https://github.com/geolonia/community-geocoder/issues/21 と同様です。
本当に恐縮です。

ただし、ご報告は遠慮なくどうぞ 😊
