### ISSUE TITLE
[誤判定] 岡山県笠岡市大冝

### ISSUE THREAD

**Issue by hamano** [geolonia/community-geocoder#24]
住所が判定できませんでした。

**Comment by miya0001** [comment]
ありがとうございます！

なるほど。国交省の位置参照情報には `大宜` となっていますね。
ちょっと調べます。

**Comment by miya0001** [comment]
Note:

ひらがなではないが対処方法は同じなので、「誤判定:ひらがな」のラベルをつけた。
