### ISSUE TITLE
[誤判定] 三重県名張市桔梗が丘

### ISSUE THREAD

**Issue by y-goto** [geolonia/community-geocoder#27]
三重県名張市の住宅地の名前ですが、桔梗が丘ではなく三重県名張市赤目町一ノ井になってしまいました。
また、桔梗が丘をはじめ、名張市のこのような住宅地では「桔梗が丘A番町B街区C番地(のD)」となっていたり「南1番町」だったりして、他の地域とは異なるかなり変則的な名前になっています。

**Comment by miya0001** [comment]
ありがとうございます！

このジオコーダーは、「大字町丁目」レベルまでしか対応していなくて、こちらで確認した結果、意図したとおりには判別できているようです。
まだまだイマイチな精度で恐縮ですが、これから育てていくところですので気長に見守っていただけると幸いです。

というわけで本件閉じさせていただきます。ありがとうございました！
