### ISSUE TITLE
正しい位置に飛ばない: 京都府乙訓郡大山崎町下植野宮脇1-88

### ISSUE THREAD

**Issue by yumetodo** [geolonia/community-geocoder#28]
`京都府乙訓郡大山崎町下植野宮脇1-88`を検索したところ、正しい位置に飛ばない。

actual

![image](https://user-images.githubusercontent.com/10869046/83755602-c8b14a00-a6a8-11ea-9e09-5fe7df241ad4.png)

expected

![image](https://user-images.githubusercontent.com/10869046/83755655-d8c92980-a6a8-11ea-8957-590ebe437e65.png)

**Comment by miya0001** [comment]
ありがとうございます！

このジオコーダーは、「大字町丁目」レベルまでしか対応していなくて、こちらで確認した結果これでも意図したとおりには住所を判別できているようです。
まだまだイマイチな精度で恐縮ですが、これから育てていくところですので気長に見守っていただけると幸いです。

というわけで本件閉じさせていただきます。ありがとうございました！

**Comment by yumetodo** [comment]
なるほど、ありがとうございました。
