### ISSUE TITLE
[誤判定] 愛媛県松山市福角町甲208番地11

### ISSUE THREAD

**Issue by arai-wa** [geolonia/community-geocoder#29]
「誤判定を報告」リンクが表示されないので手動でIssueを作成しました。

愛媛県松山市福角町甲208番地11 の緯度経度が正しく表示されていませんでした。
グーグルマップで「愛媛県松山市福角町甲208-11」を検索してヒットするのが正しい位置です。
（グーグルマップでも愛媛県松山市福角町甲208番地11はヒットしません）

関係の有無は不明ですが愛媛県松山市福角町は、それ以降に甲がつく住所とつかない住所の両方が存在するようです。

**Comment by miya0001** [comment]
ありがとうございます！

このジオコーダーは、「大字町丁目」レベルまでしか対応していなくて、こちらで確認した結果、意図したとおりには判別できているようです。
まだまだイマイチな精度で恐縮ですが、これから育てていくところですので気長に見守っていただけると幸いです。

というわけで本件閉じさせていただきます。ありがとうございました！
