### ISSUE TITLE
[誤判定] 旭川市 2桁の「丁目」

### ISSUE THREAD

**Issue by ykato** [geolonia/community-geocoder#30]
1桁の「n丁目」であればOKですが、2桁の「nn丁目」になると「見つかりません」になりました。

- 旭川市神居2条10丁目
- 旭川市神楽6条12丁目
- 旭川市5条通20丁目
- 旭川市永山3条19丁目
- 旭川市永山町14丁目
- 旭川市近文町17丁目2699番地ﾉ5
- 旭川市川端町7条10丁目
- 旭川市東光9条10丁目

以下については2桁のnn丁目のみ存在します。

- 旭川市南5条通20丁目
- 旭川市錦町14丁目
- 旭川市緑町15丁目-

**Comment by miya0001** [comment]
ありがとうございます！

**Comment by miya0001** [comment]
詳細は #43 を参照

**Comment by miya0001** [comment]
#43 は関係なさそう。

**Comment by miya0001** [comment]
Fixed on https://github.com/geolonia/community-geocoder/commit/007195f7e83fefd16632c681ffd50d16ca1febe7
