### ISSUE TITLE
[誤判定] 北海道上川郡鷹栖町, 北海道旭川市東鷹栖の n線m号

### ISSUE THREAD

**Issue by ykato** [geolonia/community-geocoder#31]
住所が判定できませんでした。

北海道上川郡鷹栖町9線6号
北海道旭川市東鷹栖10線21号

**Comment by HiraSeal** [comment]
北海道の○線シリーズなので、こちらに追記しますが、

北海道旭川市西神楽一線13号841-2
だと判定できて
北海道旭川市西神楽1線13号841-2
だと判定できませんでした。

※北海道上川郡鷹栖町九線6号 なら判定できますね。
