### ISSUE TITLE
[誤判定] 京都府京都市下京区東松屋町、西松屋町、松屋町

### ISSUE THREAD

**Issue by akazs** [geolonia/community-geocoder#37]
京都府京都市下京区に東松屋町、西松屋町、松屋町があります。
（それぞれ一つのみでかぶりはありません）
すべてが松屋町に判定されているようです。

**Comment by miya0001** [comment]
ありがとうございます！

**Comment by miya0001** [comment]
Note:

京都の通り名に対処するために後方一致でマッチさせたことが裏目に出てるっぽいですね。

* 同様の不具合は京都以外では無い気がしますが一応チェックすること
* 町名を文字数が多い順にソートしてループで回すと解決しそうですね。

https://github.com/geolonia/community-geocoder/blob/master/src/imi-enrichment-address/lib/find.js#L177-L189
