### ISSUE TITLE
東京都中央区銀座西2丁目2番地先

### ISSUE THREAD

**Issue by tsugumi** [geolonia/community-geocoder#39]
銀座インズ2の住所。銀座インズ3も同様。

**Comment by miya0001** [comment]
ありがとうございます！

このジオコーダーは、「大字町丁目」レベルまでしか対応していなくて、こちらで確認した結果、意図したとおりには判別できているようです。
まだまだイマイチな精度で恐縮ですが、これから育てていくところですので気長に見守っていただけると幸いです。

というわけで本件閉じさせていただきます。ありがとうございました！
