### ISSUE TITLE
[誤判定] 福岡県遠賀郡水巻町杁

### ISSUE THREAD

**Issue by umacocco** [geolonia/community-geocoder#41]
重箱の隅をつつくような指摘で誠に恐縮なのですが、福岡県遠賀郡水巻町えぶりを元の漢字で杁と入力したところ、住所が判定できませんでした。
自分も当て込む先のコードの違いこそあれ同じようなことを行っているのですが、こういった表記揺れも出てくるたびちまちま対応しないといけないのがしんどいですね…

**Comment by kamataryo** [comment]
さいたま市と埼玉市のケースなどの自治体レベルのケースでしたらある程度コントロールできそうですが、それよりも小さい単位で地域固有の慣習の表記揺れがあると扱いが難しいですね..
情報ありがとうございます！
