### ISSUE TITLE
[誤判定] 静岡県掛川市上屋敷１１−１５

### ISSUE THREAD

**Issue by kgSuzuki1994** [geolonia/community-geocoder#43]
住所が判定できませんでした。

**Comment by miya0001** [comment]
ありがとうございます！

**Comment by miya0001** [comment]
Note:

* 位置参照情報には該当する住所があるのでパーサーのバグっぽい。

```
  "22213掛川市": {
   （中略）
   "0043上屋敷": 0,
```

**Comment by miya0001** [comment]
国交省の位置参照情報のデータが、現在ダウンロードできるデータの内容と IMI ツールに同梱されているデータの内容で値が違うことによるエラーの模様。

最新: `222130042`
IMI ツールに同梱のデータ: `222130043`

IMI ツールのデータの出元が現状はよくわからない。
https://github.com/IMI-Tool-Project/imi-enrichment-address/issues/1

さらに、IMI ツールで CSV に対して何らかの加工をしているので、同様の下処理をする必要があるのかもしれない。

https://github.com/IMI-Tool-Project/imi-enrichment-address/blob/master/tools/download.sh#L20-L38
