### ISSUE TITLE
[誤判定] 北海道上川郡東神楽町19号南2番地

### ISSUE THREAD

**Issue by ykato** [geolonia/community-geocoder#47]
住所が判定できませんでした。

NG: 北海道上川郡東神楽町19号南2番地
OK: 北海道上川郡東神楽町十九号南2番地

NG: 北海道上川郡東川町西3号北7番地
OK: 北海道上川郡東川町西三号北7番地

「n線」がつかない住所なので別issueにしました。

**Comment by kamataryo** [comment]
ありがとうございます！
