### ISSUE TITLE
大阪市西区千代崎3丁目南2

### ISSUE THREAD

**Issue by dai991** [geolonia/community-geocoder#57]
千代崎三丁目（大阪ドームのあるあたりです）の住居表示は丁目の後に北2,中2,南2となる箇所があります。その判定ができていないように見受けられます。

**Comment by kamataryo** [comment]
ありがとうございます！

**Comment by dai991** [comment]
表記が間違っていましたので訂正しました。

**Comment by miya0001** [comment]
@dai991 

ご報告ありがとうございます！

このジオコーダーは、「大字町丁目」レベルまでしか対応していなくて、こちらで確認した結果、意図したとおりには判別できているようです。
まだまだイマイチな精度で恐縮ですが、これから育てていくところですので気長に見守っていただけると幸いです。

というわけで本件閉じさせていただきます。ありがとうございました！
