### ISSUE TITLE
ひらがなやカタカナやローマ字のみでの検索ができません

### ISSUE THREAD

**Issue by Asugakoisi** [geolonia/community-geocoder#79]
タイトルのまんまですが、ひらがなやカタカナやローマ字のみでの検索ができません。
外国人の方が利用される場合は、ローマ字入力できることが必須になると思うので、ローマ字検索だけでも実装するのはいかがでしょうか。

**Comment by miya0001** [comment]
ありがとうございます！

静的なファイルを使ったオープンソースのジオコーダーという趣旨で考えると、仕組み的に難しいと思います。
弊社では別途会員向けのジオコーダーを提供する予定なのでそちらでは対応可能です。

というわけで、閉じさせていただきます。
