### ISSUE TITLE
[誤判定] 茨城県龍ケ崎市３７１０番地

### ISSUE THREAD

**Issue by ide-an** [geolonia/community-geocoder#94]
住所が判定できませんでした。

茨城県龍ケ崎市の市役所の住所です。
https://www.any.co.jp/%E5%9C%B0%E7%95%AA%E3%81%97%E3%81%8B%E3%81%AA%E3%81%84%E5%9C%B0%E5%90%8D%EF%BC%88%E4%BD%8F%E6%89%80%E9%9B%91%E5%AD%A6%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA2%EF%BC%89/

**Comment by ide-an** [comment]
重複だったためcloseします。
https://github.com/geolonia/community-geocoder/issues/49

**Comment by kamataryo** [comment]
ありがとうございます！
